"use client";

import { useEffect } from "react";

/**
 * Registers the service worker generated by @serwist/next at /sw.js on
 * first mount of the app. Kept as a separate client component so the root
 * layout can stay a server component.
 *
 * The SW itself uses skipWaiting + clientsClaim (see app/sw.ts) so updates
 * activate on the next page navigation without a visible "refresh" banner.
 * In dev mode @serwist/next skips compilation so the fetch will 404 —
 * silent early-return keeps the console clean.
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("serviceWorker" in navigator)) return;
    if (process.env.NODE_ENV !== "production") return;

    const register = async () => {
      try {
        await navigator.serviceWorker.register("/sw.js", { scope: "/" });
      } catch {
        // Best-effort — if the SW fails to register the app still works,
        // just without offline caching of the shell.
      }
    };

    // Defer registration to after paint so it doesn't compete with first
    // meaningful content on slow devices.
    if (document.readyState === "complete") {
      register();
    } else {
      window.addEventListener("load", register, { once: true });
    }
  }, []);

  return null;
}
