import type { Routine } from "./db";

export const BASE_ROUTINES: Omit<Routine, "id" | "createdAt" | "updatedAt">[] =
  [
    {
      name: "Lunes - Torso Completo",
      dayOfWeek: 1,
      exercises: [
        {
          id: "mon_01",
          name: "Jalón unilateral neutro",
          muscleGroup: "Espalda",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "mon_02",
          name: "Press banca mancuernas",
          muscleGroup: "Pecho",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "mon_03",
          name: "Remo pecho apoyado máquina",
          muscleGroup: "Espalda",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "6kb6uh0",
        },
        {
          id: "mon_04",
          name: "Press inclinado máquina",
          muscleGroup: "Pecho",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "6kb6uh0",
        },
        {
          id: "mon_05",
          name: "Remo en cable unilateral",
          muscleGroup: "Espalda",
          sets: 3,
          reps: "10-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "mon_06",
          name: "Elevación lateral polea",
          muscleGroup: "Hombros",
          sets: 4,
          reps: "14-16",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "q38ybcs",
        },
        {
          id: "mon_08",
          name: "Extensión tríceps katana",
          muscleGroup: "Tríceps",
          sets: 4,
          reps: "10-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "q38ybcs",
        },
        {
          id: "mon_07",
          name: "Curl inclinado mancuernas",
          muscleGroup: "Bíceps",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "061zmjp",
        },
        {
          id: "mon_09",
          name: "Encogimiento máquina con pausa",
          muscleGroup: "Trapecio",
          sets: 4,
          reps: "10-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "061zmjp",
        },
        {
          id: "mon_10",
          name: "Curl araña",
          muscleGroup: "Bíceps",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "mon_11",
          name: "Extensión de tríceps en máquina",
          muscleGroup: "Tríceps",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
      ],
    },
    {
      name: "Martes - Pierna + Core",
      dayOfWeek: 2,
      exercises: [
        {
          id: "tue_01",
          name: "Aductor máquina",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 85,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "tue_03",
          name: "Hack squat profundo",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "8-10",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "tue_04",
          name: "Prensa inclinada pies bajos",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "tue_07",
          name: "Hip thrust",
          muscleGroup: "Glúteos",
          sets: 3,
          reps: "8-10",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "tue_05",
          name: "Curl femoral sentado",
          muscleGroup: "Piernas",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "tnxtcqx",
        },
        {
          id: "tue_06",
          name: "Extensión unilateral",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "tnxtcqx",
        },
        {
          id: "tue_02",
          name: "Abducción máquina",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "rryfhj9",
        },
        {
          id: "tue_08",
          name: "Gemelo de pie",
          muscleGroup: "Gemelos",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "rryfhj9",
        },
        {
          id: "tue_09",
          name: "Gemelo sentado",
          muscleGroup: "Gemelos",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "tue_10",
          name: "Russian Twist",
          muscleGroup: "Core",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "tue_11",
          name: "Elevación lateral polea",
          muscleGroup: "Hombros",
          sets: 4,
          reps: "14-16",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "g4qafa0",
        },
        {
          id: "tue_12",
          name: "Crunch polea ABS",
          muscleGroup: "Core",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "g4qafa0",
        },
      ],
    },
    {
      name: "Jueves - Torso Variación",
      dayOfWeek: 4,
      exercises: [
        {
          id: "thu_01",
          name: "Press militar máquina",
          muscleGroup: "Hombros",
          sets: 3,
          reps: "10-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "y8ynskq",
        },
        {
          id: "thu_02",
          name: "Curl predicador mancuerna",
          muscleGroup: "Bíceps",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "9gwgy04",
        },
        {
          id: "thu_03",
          name: "Extensión tríceps polea unilateral",
          muscleGroup: "Tríceps",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "9gwgy04",
        },
        {
          id: "thu_04",
          name: "Remo T-bar pecho apoyado",
          muscleGroup: "Espalda",
          sets: 4,
          reps: "8-10",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "thu_05",
          name: "Face pull pesado",
          muscleGroup: "Espalda",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "thu_06",
          name: "Press de pecho en máquina",
          muscleGroup: "Pecho",
          sets: 3,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "thu_07",
          name: "Press francés con mancuernas",
          muscleGroup: "Tríceps",
          sets: 4,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "thu_08",
          name: "Curl martillo polea",
          muscleGroup: "Bíceps",
          sets: 4,
          reps: "10-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "mfmclju",
        },
        {
          id: "thu_09",
          name: "Elevación lateral máquina",
          muscleGroup: "Hombros",
          sets: 4,
          reps: "14-16",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "mfmclju",
        },
        {
          id: "thu_10",
          name: "Jalón neutro cerrado V",
          muscleGroup: "Espalda",
          sets: 3,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "qt5s9uk",
        },
        {
          id: "thu_11",
          name: "Aperturas en máquina",
          muscleGroup: "Pecho",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "qt5s9uk",
        },
        {
          id: "thu_12",
          name: "Pájaros peck deck",
          muscleGroup: "Hombros",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
      ],
    },
    {
      name: "Viernes - Pierna + Posterior",
      dayOfWeek: 5,
      exercises: [
        {
          id: "fri_01",
          name: "Aductor máquina",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "fri_03",
          name: "Sentadilla libre",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "8-10",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
        },
        {
          id: "fri_04",
          name: "Peso muerto rumano con mancuernas",
          muscleGroup: "Piernas",
          sets: 4,
          reps: "8-10",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "fri_05",
          name: "Bulgara",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "8-12",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "fri_06",
          name: "Curl femoral acostado",
          muscleGroup: "Piernas",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "6f4qfrg",
        },
        {
          id: "fri_07",
          name: "Extensión cuádriceps",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "6f4qfrg",
        },
        {
          id: "fri_02",
          name: "Abducción máquina",
          muscleGroup: "Piernas",
          sets: 3,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "p7icoh4",
        },
        {
          id: "fri_08",
          name: "Gemelo sentado",
          muscleGroup: "Gemelos",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "p7icoh4",
        },
        {
          id: "fri_09",
          name: "Elevaciones piernas colgado ABS",
          muscleGroup: "Core",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 150,
        },
        {
          id: "fri_10",
          name: "Face pull pesado",
          muscleGroup: "Espalda",
          sets: 4,
          reps: "12-15",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 30,
          supersetId: "nsq9iqt",
        },
        {
          id: "fri_11",
          name: "Farmer walk pesado",
          muscleGroup: "Trapecio",
          sets: 4,
          reps: "40m",
          targetWeight: 0,
          unit: "kg",
          restSeconds: 180,
          supersetId: "nsq9iqt",
        },
      ],
    },
  ];
