import type { Equipment } from "./db";

/**
 * Curated catalog of common gym equipment, bundled with the app.
 *
 * Each entry declares the movement, muscles worked, weight range, and —
 * critically — the minimum available weight increment. The RPE engine uses
 * `increment` (and `microIncrement` when available) to scale recommendations:
 * a machine with a 5 kg stack step won't get a "+2 kg" suggestion.
 *
 * Notes on the numbers:
 * - Free-weight bar/dumbbell min weights reflect typical commercial gym
 *   setups; many gyms have lighter dumbbells, users can still log 0 or
 *   define a custom entry.
 * - Machine stack increments follow the most common convention. Modern
 *   plate-loaded machines accept 1.25 kg microplates, so `microIncrement`
 *   is set on them.
 * - `minWeight` for machines = carriage/sled weight where publicly known;
 *   otherwise 0. It's advisory, not enforced.
 * - Research confirmed no public API exposes this data; these are manually
 *   compiled from REP Fitness, Freedom Fitness, and manufacturer spec
 *   sheets (Life Fitness, Hammer Strength, Matrix, Cybex, Technogym).
 */

type CatalogEntry = Omit<Equipment, "isCustom" | "createdAt">;

function make(entry: CatalogEntry): Equipment {
  return { ...entry, isCustom: false };
}

export const EQUIPMENT_CATALOG: Equipment[] = [
  // ────────── PECHO ──────────
  make({
    id: "cat_barbell_bench_press",
    name: "Press banca con barra",
    type: "barbell",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_barbell_incline_bench",
    name: "Press banca inclinado con barra",
    type: "barbell",
    muscleGroups: ["Pecho", "Hombros", "Triceps"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dumbbell_bench_press",
    name: "Press banca con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dumbbell_incline_press",
    name: "Press inclinado con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Pecho", "Hombros", "Triceps"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_machine_chest_press",
    name: "Press pecho máquina",
    type: "machine_stack",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 120,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_plate_chest_press",
    name: "Press pecho plate-loaded",
    type: "plate_loaded",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_pec_deck",
    name: "Aperturas máquina (pec deck)",
    type: "machine_stack",
    muscleGroups: ["Pecho"],
    movement: "isolation",
    minWeight: 5,
    maxWeight: 90,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_cable_fly",
    name: "Aperturas en polea",
    type: "cable",
    muscleGroups: ["Pecho"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 80,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_dips",
    name: "Fondos en paralelas",
    type: "bodyweight",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),
  make({
    id: "cat_pushup",
    name: "Flexiones",
    type: "bodyweight",
    muscleGroups: ["Pecho", "Triceps", "Hombros"],
    movement: "compound",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),

  // ────────── ESPALDA ──────────
  make({
    id: "cat_barbell_row",
    name: "Remo con barra",
    type: "barbell",
    muscleGroups: ["Espalda", "Biceps", "Trapecio"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dumbbell_row",
    name: "Remo con mancuerna unilateral",
    type: "dumbbell",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_t_bar_row",
    name: "Remo T-bar",
    type: "plate_loaded",
    muscleGroups: ["Espalda", "Biceps", "Trapecio"],
    movement: "compound",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_seated_cable_row",
    name: "Remo en polea sentado",
    type: "cable",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 100,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_machine_row",
    name: "Remo máquina",
    type: "machine_stack",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 110,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_lat_pulldown",
    name: "Jalón al pecho",
    type: "cable",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 110,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_neutral_pulldown",
    name: "Jalón neutro unilateral",
    type: "cable",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 80,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_pullup",
    name: "Dominadas",
    type: "bodyweight",
    muscleGroups: ["Espalda", "Biceps"],
    movement: "compound",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),
  make({
    id: "cat_face_pull",
    name: "Face pull",
    type: "cable",
    muscleGroups: ["Hombros", "Espalda"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 50,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_straight_arm_pulldown",
    name: "Pullover en polea",
    type: "cable",
    muscleGroups: ["Espalda"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 70,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_deadlift",
    name: "Peso muerto",
    type: "barbell",
    muscleGroups: ["Espalda", "Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_rumanian_deadlift",
    name: "Peso muerto rumano",
    type: "barbell",
    muscleGroups: ["Piernas", "Gluteos", "Espalda"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_shrug_barbell",
    name: "Encogimientos con barra",
    type: "barbell",
    muscleGroups: ["Trapecio"],
    movement: "isolation",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_shrug_dumbbell",
    name: "Encogimientos con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Trapecio"],
    movement: "isolation",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),

  // ────────── PIERNAS (cuádriceps/glúteos/isquios) ──────────
  make({
    id: "cat_barbell_squat",
    name: "Sentadilla con barra",
    type: "barbell",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_front_squat",
    name: "Sentadilla frontal",
    type: "barbell",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_hack_squat",
    name: "Hack squat",
    type: "plate_loaded",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 25,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_leg_press_45",
    name: "Prensa 45°",
    type: "plate_loaded",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 25,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_leg_press_horizontal",
    name: "Prensa horizontal (stack)",
    type: "machine_stack",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 10,
    maxWeight: 200,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_smith_squat",
    name: "Sentadilla en Smith",
    type: "smith",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 15,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_bulgarian_split",
    name: "Búlgara con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_walking_lunge",
    name: "Zancadas caminando",
    type: "dumbbell",
    muscleGroups: ["Piernas", "Gluteos"],
    movement: "compound",
    minWeight: 0,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_leg_extension",
    name: "Extensión de cuádriceps",
    type: "machine_stack",
    muscleGroups: ["Piernas"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 100,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_leg_curl_lying",
    name: "Curl femoral tumbado",
    type: "machine_stack",
    muscleGroups: ["Piernas"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 90,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_leg_curl_seated",
    name: "Curl femoral sentado",
    type: "machine_stack",
    muscleGroups: ["Piernas"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 90,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_nordic_curl",
    name: "Nordic curl",
    type: "bodyweight",
    muscleGroups: ["Piernas"],
    movement: "isolation",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),
  make({
    id: "cat_adductor_machine",
    name: "Aductor máquina",
    type: "machine_stack",
    muscleGroups: ["Piernas"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 90,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_abductor_machine",
    name: "Abductor máquina",
    type: "machine_stack",
    muscleGroups: ["Gluteos"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 90,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_hip_thrust",
    name: "Hip thrust con barra",
    type: "barbell",
    muscleGroups: ["Gluteos", "Piernas"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_glute_kickback",
    name: "Patada glúteo en polea",
    type: "cable",
    muscleGroups: ["Gluteos"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 50,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),

  // ────────── PANTORRILLAS ──────────
  make({
    id: "cat_standing_calf",
    name: "Gemelo de pie máquina",
    type: "machine_stack",
    muscleGroups: ["Pantorrillas"],
    movement: "isolation",
    minWeight: 5,
    maxWeight: 150,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_seated_calf",
    name: "Gemelo sentado",
    type: "plate_loaded",
    muscleGroups: ["Pantorrillas"],
    movement: "isolation",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_donkey_calf",
    name: "Gemelo tipo burro",
    type: "plate_loaded",
    muscleGroups: ["Pantorrillas"],
    movement: "isolation",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "settings",
  }),

  // ────────── HOMBROS ──────────
  make({
    id: "cat_barbell_ohp",
    name: "Press militar con barra",
    type: "barbell",
    muscleGroups: ["Hombros", "Triceps"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dumbbell_ohp",
    name: "Press militar con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Hombros", "Triceps"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_machine_shoulder_press",
    name: "Press militar máquina",
    type: "machine_stack",
    muscleGroups: ["Hombros", "Triceps"],
    movement: "compound",
    minWeight: 5,
    maxWeight: 100,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_arnold_press",
    name: "Arnold press",
    type: "dumbbell",
    muscleGroups: ["Hombros"],
    movement: "compound",
    minWeight: 2,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_lateral_raise_db",
    name: "Elevaciones laterales con mancuerna",
    type: "dumbbell",
    muscleGroups: ["Hombros"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_lateral_raise_cable",
    name: "Elevaciones laterales en polea",
    type: "cable",
    muscleGroups: ["Hombros"],
    movement: "isolation",
    minWeight: 1.25,
    maxWeight: 40,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_lateral_raise_machine",
    name: "Elevaciones laterales máquina",
    type: "machine_stack",
    muscleGroups: ["Hombros"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 60,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_rear_delt_fly",
    name: "Pájaros / rear delt fly",
    type: "dumbbell",
    muscleGroups: ["Hombros", "Espalda"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_rear_delt_machine",
    name: "Rear delt máquina",
    type: "machine_stack",
    muscleGroups: ["Hombros"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 80,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_front_raise",
    name: "Elevaciones frontales",
    type: "dumbbell",
    muscleGroups: ["Hombros"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_upright_row",
    name: "Remo al mentón",
    type: "barbell",
    muscleGroups: ["Hombros", "Trapecio"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),

  // ────────── BÍCEPS ──────────
  make({
    id: "cat_barbell_curl",
    name: "Curl con barra",
    type: "barbell",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    microIncrement: 1.25,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dumbbell_curl",
    name: "Curl con mancuernas",
    type: "dumbbell",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_incline_curl",
    name: "Curl inclinado",
    type: "dumbbell",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_preacher_curl",
    name: "Curl predicador máquina",
    type: "machine_stack",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 70,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_preacher_curl_barbell",
    name: "Curl predicador con barra",
    type: "barbell",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_hammer_curl",
    name: "Curl martillo",
    type: "dumbbell",
    muscleGroups: ["Biceps", "Antebrazos"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_cable_curl",
    name: "Curl en polea",
    type: "cable",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 60,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_spider_curl",
    name: "Curl araña",
    type: "dumbbell",
    muscleGroups: ["Biceps"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),

  // ────────── TRÍCEPS ──────────
  make({
    id: "cat_close_grip_bench",
    name: "Press banca agarre cerrado",
    type: "barbell",
    muscleGroups: ["Triceps", "Pecho"],
    movement: "compound",
    minWeight: 20,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_triceps_pushdown",
    name: "Extensión tríceps en polea",
    type: "cable",
    muscleGroups: ["Triceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 80,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_triceps_rope",
    name: "Tríceps en polea con cuerda",
    type: "cable",
    muscleGroups: ["Triceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 60,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_overhead_triceps",
    name: "Extensión tríceps por encima",
    type: "cable",
    muscleGroups: ["Triceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 50,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_triceps_machine",
    name: "Extensión tríceps máquina",
    type: "machine_stack",
    muscleGroups: ["Triceps"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 70,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_skullcrusher",
    name: "Skullcrusher (press francés)",
    type: "barbell",
    muscleGroups: ["Triceps"],
    movement: "isolation",
    minWeight: 10,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_dips_triceps",
    name: "Fondos para tríceps (banco)",
    type: "bodyweight",
    muscleGroups: ["Triceps", "Pecho"],
    movement: "compound",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),

  // ────────── ANTEBRAZOS ──────────
  make({
    id: "cat_wrist_curl",
    name: "Curl de muñeca",
    type: "dumbbell",
    muscleGroups: ["Antebrazos"],
    movement: "isolation",
    minWeight: 1,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_farmer_walk",
    name: "Farmer walk",
    type: "dumbbell",
    muscleGroups: ["Antebrazos", "Trapecio"],
    movement: "compound",
    minWeight: 5,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),

  // ────────── CORE / ABDOMINALES ──────────
  make({
    id: "cat_cable_crunch",
    name: "Crunch en polea",
    type: "cable",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 80,
    increment: 2.5,
    unit: "kg",
    icon: "cable",
  }),
  make({
    id: "cat_ab_machine",
    name: "Abdominales máquina",
    type: "machine_stack",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 2.5,
    maxWeight: 100,
    increment: 5,
    microIncrement: 2.5,
    unit: "kg",
    icon: "settings",
  }),
  make({
    id: "cat_hanging_leg_raise",
    name: "Elevación de piernas colgado",
    type: "bodyweight",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),
  make({
    id: "cat_plank",
    name: "Plancha (plank)",
    type: "bodyweight",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),
  make({
    id: "cat_russian_twist",
    name: "Russian twist",
    type: "dumbbell",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 0,
    maxWeight: null,
    increment: 1,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_crunch",
    name: "Crunch en suelo",
    type: "bodyweight",
    muscleGroups: ["Abdominales"],
    movement: "isolation",
    minWeight: 0,
    maxWeight: null,
    increment: 1.25,
    unit: "kg",
    icon: "activity",
  }),

  // ────────── CARDIO / FULL BODY (mínimos) ──────────
  make({
    id: "cat_thruster",
    name: "Thruster",
    type: "barbell",
    muscleGroups: ["Full Body"],
    movement: "compound",
    minWeight: 15,
    maxWeight: null,
    increment: 2.5,
    unit: "kg",
    icon: "dumbbell",
  }),
  make({
    id: "cat_kettlebell_swing",
    name: "Kettlebell swing",
    type: "custom",
    muscleGroups: ["Full Body", "Gluteos", "Espalda"],
    movement: "compound",
    minWeight: 8,
    maxWeight: null,
    increment: 4,
    unit: "kg",
    icon: "dumbbell",
  }),
];

/** Ordered list of unique muscle groups used in the catalog, for the filter UI. */
export const CATALOG_MUSCLE_GROUPS = Array.from(
  new Set(EQUIPMENT_CATALOG.flatMap((e) => e.muscleGroups)),
).sort();

/** Equipment types grouped with UI-friendly labels. */
export const EQUIPMENT_TYPE_LABELS: Record<string, string> = {
  barbell: "Barra libre",
  dumbbell: "Mancuernas",
  machine_stack: "Máquina (placas en stack)",
  machine_stack_fine: "Máquina (stack fino)",
  plate_loaded: "Máquina plate-loaded",
  cable: "Polea",
  smith: "Máquina Smith",
  bodyweight: "Peso corporal",
  custom: "Personalizado",
};

/** Helper to find a catalog entry by id. */
export function findCatalogEquipment(id: string | undefined | null) {
  if (!id) return undefined;
  return EQUIPMENT_CATALOG.find((e) => e.id === id);
}
